### ISSUE TITLE
Some things in the template are hardcorded

### ISSUE THREAD

**Issue by simonv3** [bnvk/Beardo#14]
For example: name of the template, email address, name of the contractor, tax id number, currency, etc.

I'm happy taking steps to make them more modular, though I'm not sure what you're thinking is stored in the data.json file and what isn't. This might need to be saved in a different place (as it doesn't conform to the data being handled by the schema?)

May be a duplicate of #7.

**Comment by bnvk** [comment]
@simonv3 really good questions and catch, thanks for bringing this up! It's definitely something on my radar. I do err towards thinking it needs to be saved in a different place as you suggest. However, I'm not sure where that place might be.

My overall current vision for Beardo (which is much larger in scope than this issue) but I think contains the answer to your question is:

- Allow inputs of numerous different data sets, so `current-clients.csv, old-clients.csv, etc...` 
- Run filters / display options on data across all input sets
- Define output means `html, pdf, etc...`
- Offer different **"Output Templates"** of which `invoices` are only one type

So yah, I think you mentioning #7 is correct, although this is not a duplicate, but rather a subset or component.

**Comment by simonv3** [comment]
Would it make sense to have a second data CSV and JSON combo that is user information? With a db powered backend you'd have that anyway.

**Comment by bnvk** [comment]
Yah... perhaps that is the right way to go. I was hoping to stay away from db dependencies as a lil experiment- but a few blobs of "user settings" and schema JSON should get us quite far. Here's the sort of UX / app flow I was thinking once we get Beardo to have an actual CLI #17 then the following is my vision for what I'd call a significant release:

[Read IDEAS file](https://github.com/bnvk/Beardo/blob/master/IDEAS.md)

Anywho, that's what my current vision is... thoughts? :)

**Comment by simonv3** [comment]
That's way more meta than I thought you were aiming for. 

So the idea is that using any input, you could choose from a series of "spells", and then you map the data in CSV (or whatever) to the inputs of the spell. I think I get it. The idea being that someone could bring in data from anywhere, and Beardo will be able to magically create graphs and such from it, or convert it to Beardo standard CSV. Is that right?

I'll admit that for my "right here right now" scenario I'm not sure how I'd use that.

**Comment by bnvk** [comment]
@simonv3 hehe, yah, maybe I got a little bit too meta there. But yes, you get the idea `someone could bring in data from anywhere, and Beardo will be able to magically create graphs and such from it` that's the goal. I dunno about you, but I constantly want to munge and play with lil blobs of data, not to mention need to do things like invoices. 

But, perhaps I should reign it in, and keep this to "right here right now" which is probably a good strategy :)

Onto fixing this template thing soon, I promise!

**Comment by simonv3** [comment]
I dunno, I think that's a pretty worthy long term goal. Usually I feel like clients that require hours have their invoicing tool that they want you to use, so to be able to pump that into your own template is pretty cool (and a pretty unique feature as far I can tell).

**Comment by bnvk** [comment]
@simonv3 hehe ok, I will certainly accept your pull req if you beat me to it ;) one thing to note I just added some light PDF output support as per issue #1 so that now pull from the same HTML template

**Comment by simonv3** [comment]
@bnvk Great. And I already have wkhtmltopdf installed, I'll test that out.
