### ISSUE TITLE
Track.js adds a blank line to the CSV. 

### ISSUE THREAD

**Issue by simonv3** [bnvk/Beardo#20]
Haven't quite tested whether it's after or before an entry.

This causes beardo.js to break, cause trim doesn't like blank lines.

**Comment by bnvk** [comment]
@simonv3 I'm pretty sure that is just that you had a blank line at the end of your CSV and then ran track.js on top of it... that happened to me once, re-test with no blank line plsz ;)

**Comment by simonv3** [comment]
@bnvk - you're right. I think what happens is that when I edit the CSV itself my sublime auto-adds a blank line at end.
